# Generated by Django 5.0.2 on 2024-05-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('date', models.DateField()),
            ],
        ),
    ]
